[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repositoryRoot = [System.IO.Path]::GetFullPath([System.IO.Path]::Combine($PSScriptRoot, '..', '..', '..'))
$versionScript = [System.IO.Path]::Combine($repositoryRoot, 'scripts', 'updater', 'set-application-version.ps1')
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$productName = -join @([char]0x4E03, [char]0x9171, [char]0x684C, [char]0x5BA0)
$fixturePackageName = -join @('desk', '-pet', '-framework')
$results = @()

function Add-TestResult([string]$Name, [bool]$Passed, [string]$Details) {
    $script:results += [pscustomobject]@{ Name = $Name; Passed = $Passed; Details = $Details }
}

function Test-Equal([string]$Name, [object]$Expected, [object]$Actual) {
    Add-TestResult $Name ($Expected -eq $Actual) "expected=$Expected; actual=$Actual"
}

function Test-True([string]$Name, [bool]$Actual, [string]$Details = '') {
    Add-TestResult $Name $Actual $Details
}

function Test-Throws([string]$Name, [scriptblock]$Action, [string]$Pattern) {
    try {
        & $Action | Out-Null
        Add-TestResult $Name $false 'No exception was thrown.'
    }
    catch {
        Add-TestResult $Name ([bool]($_.Exception.Message -match $Pattern)) $_.Exception.Message
    }
}

function Remove-VersionFixtureTree {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LiteralPath
    )

    if (-not [System.IO.Directory]::Exists($LiteralPath)) {
        return
    }
    foreach ($item in @(Get-ChildItem -LiteralPath $LiteralPath -Force -Recurse -ErrorAction SilentlyContinue)) {
        if (($item.Attributes -band [System.IO.FileAttributes]::ReadOnly) -ne 0) {
            $item.Attributes = $item.Attributes -bxor [System.IO.FileAttributes]::ReadOnly
        }
    }
    [System.IO.Directory]::Delete($LiteralPath, $true)
}

function Invoke-FixtureGit {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Root,

        [Parameter(Mandatory = $true)]
        [string[]]$Arguments
    )

    $previousErrorActionPreference = $ErrorActionPreference
    try {
        $ErrorActionPreference = 'Continue'
        & git -C $Root @Arguments 2>$null | Out-Null
        $gitExitCode = $LASTEXITCODE
    }
    finally {
        $ErrorActionPreference = $previousErrorActionPreference
    }
    if ($gitExitCode -ne 0) {
        throw "Fixture Git command failed: $($Arguments -join ' ')"
    }
}

function New-VersionFixture {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Parent,

        [string]$Version = '0.1.0'
    )

    $root = [System.IO.Path]::Combine($Parent, [Guid]::NewGuid().ToString('N'))
    $tauriRoot = [System.IO.Path]::Combine($root, 'src-tauri')
    [void][System.IO.Directory]::CreateDirectory($tauriRoot)

    $packageJson = @"
{
  "name": "$fixturePackageName",
  "private": true,
  "version": "$Version",
  "description": "fixture-keep-package"
}
"@
    $packageLock = @"
{
  "name": "$fixturePackageName",
  "version": "$Version",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "$fixturePackageName",
      "version": "$Version",
      "license": "fixture-keep-lock"
    },
    "node_modules/version-collision-fixture": {
      "version": "9.9.9",
      "license": "fixture-dependency-lock"
    }
  }
}
"@
    $tauriConfig = @"
{
  "`$schema": "https://schema.tauri.app/config/2",
  "productName": "$productName",
  "mainBinaryName": "desktop_pet",
  "version": "$Version",
  "identifier": "dev.deskpet.framework",
  "fixtureField": "keep-tauri"
}
"@
    $cargoManifest = @"
[package]
name = "$fixturePackageName"
version = "$Version"
description = "fixture-keep-cargo"
edition = "2021"

[dependencies]
serde = "1"
"@
    $cargoLock = @"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "$fixturePackageName"
version = "$Version"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
"@
    $schemaFixture = '{"schemaVersion":1,"fixtureField":"keep-schema"}'

    [System.IO.File]::WriteAllText([System.IO.Path]::Combine($root, 'package.json'), $packageJson, $utf8NoBom)
    [System.IO.File]::WriteAllText([System.IO.Path]::Combine($root, 'package-lock.json'), $packageLock, $utf8NoBom)
    [System.IO.File]::WriteAllText([System.IO.Path]::Combine($tauriRoot, 'tauri.conf.json'), $tauriConfig, $utf8NoBom)
    [System.IO.File]::WriteAllText([System.IO.Path]::Combine($tauriRoot, 'Cargo.toml'), $cargoManifest, $utf8NoBom)
    [System.IO.File]::WriteAllText([System.IO.Path]::Combine($tauriRoot, 'Cargo.lock'), $cargoLock, $utf8NoBom)
    [System.IO.File]::WriteAllText([System.IO.Path]::Combine($root, 'character-schema.json'), $schemaFixture, $utf8NoBom)

    Invoke-FixtureGit -Root $root -Arguments @('init', '--quiet')
    Invoke-FixtureGit -Root $root -Arguments @('config', 'user.email', 'version-fixture@example.invalid')
    Invoke-FixtureGit -Root $root -Arguments @('config', 'user.name', 'Version Fixture')
    Invoke-FixtureGit -Root $root -Arguments @('add', '--all')
    Invoke-FixtureGit -Root $root -Arguments @('commit', '--quiet', '-m', 'fixture')
    return $root
}

function Get-VersionFixtureState {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Root
    )

    $package = Get-Content -LiteralPath ([System.IO.Path]::Combine($Root, 'package.json')) -Raw -Encoding UTF8 | ConvertFrom-Json
    $packageLockText = Get-Content -LiteralPath ([System.IO.Path]::Combine($Root, 'package-lock.json')) -Raw -Encoding UTF8
    $tauri = Get-Content -LiteralPath ([System.IO.Path]::Combine($Root, 'src-tauri', 'tauri.conf.json')) -Raw -Encoding UTF8 | ConvertFrom-Json
    $cargoManifest = Get-Content -LiteralPath ([System.IO.Path]::Combine($Root, 'src-tauri', 'Cargo.toml')) -Raw -Encoding UTF8
    $cargoLock = Get-Content -LiteralPath ([System.IO.Path]::Combine($Root, 'src-tauri', 'Cargo.lock')) -Raw -Encoding UTF8
    $cargoManifestVersion = [regex]::Match($cargoManifest, '(?ms)^\[package\].*?^version\s*=\s*"([^"]+)"').Groups[1].Value
    $cargoLockName = [regex]::Escape($script:fixturePackageName)
    $cargoLockVersion = [regex]::Match($cargoLock, "(?ms)^\[\[package\]\]\r?\nname = `"$cargoLockName`"\r?\nversion = `"([^`"]+)`"").Groups[1].Value
    $packageLockVersion = [regex]::Match($packageLockText, '(?m)^ {2}"version"\s*:\s*"([^"]+)"').Groups[1].Value
    $packageLockRootVersion = [regex]::Match($packageLockText, '(?m)^ {6}"version"\s*:\s*"([^"]+)"').Groups[1].Value
    $dependencyLockVersion = [regex]::Match($packageLockText, '(?ms)"node_modules/version-collision-fixture"\s*:\s*\{.*?"version"\s*:\s*"([^"]+)"').Groups[1].Value
    $lockLicense = [regex]::Match($packageLockText, '(?m)^ {6}"license"\s*:\s*"([^"]+)"').Groups[1].Value
    return [pscustomobject]@{
        Versions = @([string]$package.version, $packageLockVersion, $packageLockRootVersion, [string]$tauri.version, $cargoManifestVersion, $cargoLockVersion)
        PackageDescription = [string]$package.description
        LockLicense = $lockLicense
        DependencyLockVersion = $dependencyLockVersion
        ProductName = [string]$tauri.productName
        MainBinaryName = [string]$tauri.mainBinaryName
        Identifier = [string]$tauri.identifier
        JsonSchema = [string]$tauri.'$schema'
        TauriFixture = [string]$tauri.fixtureField
        CargoDescriptionPreserved = [bool]($cargoManifest -match 'description = "fixture-keep-cargo"')
        SchemaText = Get-Content -LiteralPath ([System.IO.Path]::Combine($Root, 'character-schema.json')) -Raw -Encoding UTF8
    }
}

$temporaryRoot = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), 'application-version-tests-' + [Guid]::NewGuid().ToString('N'))
[void][System.IO.Directory]::CreateDirectory($temporaryRoot)
try {
    $fixtureA = New-VersionFixture -Parent $temporaryRoot
    $beforeA = Get-VersionFixtureState -Root $fixtureA
    $resultA = & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $fixtureA -Confirm:$false
    $afterA = Get-VersionFixtureState -Root $fixtureA
    Test-Equal 'Version A synchronization completes' 'Completed' ([string]$resultA.Mode)
    Test-Equal 'Version A records its target' '0.2.0-beta.1' ([string]$resultA.TargetVersion)
    Test-Equal 'All six stored version values match version A' 1 @($afterA.Versions | Select-Object -Unique).Count
    Test-Equal 'Version A is stored in all five version files' '0.2.0-beta.1' ([string]$afterA.Versions[0])
    Test-Equal 'package.json unrelated field is preserved' $beforeA.PackageDescription $afterA.PackageDescription
    Test-Equal 'package-lock.json unrelated field is preserved' $beforeA.LockLicense $afterA.LockLicense
    Test-Equal 'package-lock.json dependency version is not mistaken for the root package version' '9.9.9' $afterA.DependencyLockVersion
    Test-Equal 'Product name is preserved' $beforeA.ProductName $afterA.ProductName
    Test-Equal 'Main binary name is preserved' $beforeA.MainBinaryName $afterA.MainBinaryName
    Test-Equal 'Identifier is preserved' $beforeA.Identifier $afterA.Identifier
    Test-Equal 'Tauri JSON schema is preserved' $beforeA.JsonSchema $afterA.JsonSchema
    Test-Equal 'Tauri unrelated field is preserved' $beforeA.TauriFixture $afterA.TauriFixture
    Test-Equal 'Cargo unrelated field is preserved' $true $afterA.CargoDescriptionPreserved
    Test-Equal 'Character schemaVersion fixture is untouched' $beforeA.SchemaText $afterA.SchemaText

    $fixtureB = New-VersionFixture -Parent $temporaryRoot
    $resultB = & $versionScript -Version '0.2.1-beta.1' -RepositoryRoot $fixtureB -Confirm:$false
    $afterB = Get-VersionFixtureState -Root $fixtureB
    Test-Equal 'Version B synchronization completes' 'Completed' ([string]$resultB.Mode)
    Test-Equal 'All six stored version values match version B' 1 @($afterB.Versions | Select-Object -Unique).Count
    Test-Equal 'Version B is stored in all five version files' '0.2.1-beta.1' ([string]$afterB.Versions[0])

    $alreadyCurrentFixture = New-VersionFixture -Parent $temporaryRoot -Version '0.2.0-beta.1'
    $alreadyCurrentResult = & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $alreadyCurrentFixture -Confirm:$false
    Test-Equal 'An exactly equal version remains an AlreadyCurrent no-op' 'AlreadyCurrent' ([string]$alreadyCurrentResult.Mode)

    $equalPrecedenceFixture = New-VersionFixture -Parent $temporaryRoot -Version '1.0.0+build.1'
    Test-Throws 'A build-metadata-only change cannot masquerade as a newer updater version' {
        & $versionScript -Version '1.0.0+build.2' -RepositoryRoot $equalPrecedenceFixture -WhatIf -Confirm:$false
    } 'must have higher SemVer precedence'

    foreach ($invalidVersion in @('0.2', 'v0.2.0', '0.02.0', '0.2.0-beta.01', '0.2.0_beta')) {
        Test-Throws "Invalid SemVer is rejected: $invalidVersion" {
            & $versionScript -Version $invalidVersion -RepositoryRoot $fixtureB -Confirm:$false
        } 'Invalid semantic version'
    }

    $sensitiveInvalidVersion = 'C:\Users\private-user\updater-secret'
    $sensitiveInvalidMessage = ''
    try {
        & $versionScript -Version $sensitiveInvalidVersion -RepositoryRoot $fixtureB -WhatIf -Confirm:$false | Out-Null
    }
    catch { $sensitiveInvalidMessage = [string]$_.Exception.Message }
    Test-Equal 'Invalid-version errors are generic before the transaction' 'Invalid semantic version.' $sensitiveInvalidMessage
    Test-Equal 'Invalid-version errors do not echo path-shaped sensitive input' $false ([bool]$sensitiveInvalidMessage.Contains($sensitiveInvalidVersion))

    $inconsistentFixture = New-VersionFixture -Parent $temporaryRoot
    $inconsistentPackagePath = [System.IO.Path]::Combine($inconsistentFixture, 'package.json')
    $inconsistentText = [System.IO.File]::ReadAllText($inconsistentPackagePath)
    $inconsistentSensitiveValue = 'private-user-secret-value'
    $inconsistentText = $inconsistentText.Replace('"version": "0.1.0"', '"version": "' + $inconsistentSensitiveValue + '"')
    [System.IO.File]::WriteAllText($inconsistentPackagePath, $inconsistentText, $utf8NoBom)
    Invoke-FixtureGit -Root $inconsistentFixture -Arguments @('add', 'package.json')
    Invoke-FixtureGit -Root $inconsistentFixture -Arguments @('commit', '-m', 'create inconsistent version fixture')
    $inconsistentMessage = ''
    try {
        & $versionScript -Version '0.2.0' -RepositoryRoot $inconsistentFixture -WhatIf -Confirm:$false | Out-Null
    }
    catch { $inconsistentMessage = [string]$_.Exception.Message }
    Test-Equal 'Inconsistent-version errors are generic before the transaction' `
        'Existing application versions are inconsistent across the required version files.' $inconsistentMessage
    Test-Equal 'Inconsistent-version errors do not echo stored sensitive values' $false `
        ([bool]$inconsistentMessage.Contains($inconsistentSensitiveValue))

    $downgradeFixture = New-VersionFixture -Parent $temporaryRoot -Version '0.2.0-beta.1'
    Test-Throws 'Version synchronization rejects a downgrade' {
        & $versionScript -Version '0.1.9' -RepositoryRoot $downgradeFixture -WhatIf -Confirm:$false
    } 'must have higher SemVer precedence'

    $invalidRoot = 'invalid-root-' + [char]0 + '-private-path'
    $invalidRootMessage = ''
    try {
        & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $invalidRoot -WhatIf -Confirm:$false | Out-Null
    }
    catch {
        $invalidRootMessage = [string]$_.Exception.Message
    }
    Test-Equal 'Invalid repository roots use a redacted generic error' 'Application version repository path is invalid.' $invalidRootMessage
    Test-Equal 'Invalid repository errors do not echo the supplied path' $false ([bool]$invalidRootMessage.Contains('private-path'))

    $lockedReadFixture = New-VersionFixture -Parent $temporaryRoot
    $lockedReadState = [pscustomobject]@{
        Path = [System.IO.Path]::Combine($lockedReadFixture, 'package.json')
        Stream = $null
    }
    $lockBeforeFileRead = {
        $lockedReadState.Stream = [System.IO.File]::Open(
            $lockedReadState.Path,
            [System.IO.FileMode]::Open,
            [System.IO.FileAccess]::ReadWrite,
            [System.IO.FileShare]::None
        )
    }.GetNewClosure()
    $lockedReadMessage = ''
    $previousReadTestMode = $env:DESK_PET_VERSION_TEST_MODE
    try {
        $env:DESK_PET_VERSION_TEST_MODE = '1'
        & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $lockedReadFixture `
            -TestBeforeFileReadAction $lockBeforeFileRead -WhatIf -Confirm:$false | Out-Null
    }
    catch {
        $lockedReadMessage = [string]$_.Exception.Message
    }
    finally {
        if ($null -ne $lockedReadState.Stream) { $lockedReadState.Stream.Dispose() }
        $env:DESK_PET_VERSION_TEST_MODE = $previousReadTestMode
    }
    Test-Equal 'Preflight text-read failures expose only the safe file name' 'Unable to read required application version file: package.json' $lockedReadMessage
    Test-Equal 'Preflight text-read failures do not reveal the fixture absolute path' $false ([bool]$lockedReadMessage.Contains($lockedReadFixture))

    $lockedBomFixture = New-VersionFixture -Parent $temporaryRoot
    $lockedBomState = [pscustomobject]@{
        Path = [System.IO.Path]::Combine($lockedBomFixture, 'src-tauri', 'Cargo.lock')
        Stream = $null
    }
    $lockBeforeBomRead = {
        $lockedBomState.Stream = [System.IO.File]::Open(
            $lockedBomState.Path,
            [System.IO.FileMode]::Open,
            [System.IO.FileAccess]::ReadWrite,
            [System.IO.FileShare]::None
        )
    }.GetNewClosure()
    $lockedBomMessage = ''
    $previousBomTestMode = $env:DESK_PET_VERSION_TEST_MODE
    try {
        $env:DESK_PET_VERSION_TEST_MODE = '1'
        & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $lockedBomFixture `
            -TestBeforeBomReadAction $lockBeforeBomRead -WhatIf -Confirm:$false | Out-Null
    }
    catch {
        $lockedBomMessage = [string]$_.Exception.Message
    }
    finally {
        if ($null -ne $lockedBomState.Stream) { $lockedBomState.Stream.Dispose() }
        $env:DESK_PET_VERSION_TEST_MODE = $previousBomTestMode
    }
    Test-Equal 'Preflight byte-read failures expose only the safe file name' 'Unable to inspect required application version file encoding: Cargo.lock' $lockedBomMessage
    Test-Equal 'Preflight byte-read failures do not reveal the fixture absolute path' $false ([bool]$lockedBomMessage.Contains($lockedBomFixture))

    $whatIfFixture = New-VersionFixture -Parent $temporaryRoot
    $whatIfFiles = @('package.json', 'package-lock.json', 'src-tauri\tauri.conf.json', 'src-tauri\Cargo.toml', 'src-tauri\Cargo.lock')
    $whatIfBefore = @{}
    foreach ($relativePath in $whatIfFiles) {
        $whatIfBefore[$relativePath] = [System.IO.File]::ReadAllBytes([System.IO.Path]::Combine($whatIfFixture, $relativePath))
    }
    $whatIfResult = & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $whatIfFixture -WhatIf -Confirm:$false
    Test-Equal 'WhatIf returns preview mode' 'PreviewOnly' ([string]$whatIfResult.Mode)
    foreach ($relativePath in $whatIfFiles) {
        $afterBytes = [System.IO.File]::ReadAllBytes([System.IO.Path]::Combine($whatIfFixture, $relativePath))
        Test-Equal "WhatIf leaves $relativePath byte-for-byte unchanged" ([Convert]::ToBase64String($whatIfBefore[$relativePath])) ([Convert]::ToBase64String($afterBytes))
    }

    $dirtyFixture = New-VersionFixture -Parent $temporaryRoot
    [System.IO.File]::WriteAllText([System.IO.Path]::Combine($dirtyFixture, 'untracked.txt'), 'dirty', $utf8NoBom)
    Test-Throws 'A dirty fixture worktree is rejected' {
        & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $dirtyFixture -WhatIf -Confirm:$false
    } 'working tree is not clean'

    $rollbackFixture = New-VersionFixture -Parent $temporaryRoot
    $rollbackFiles = @('package.json', 'package-lock.json', 'src-tauri\tauri.conf.json', 'src-tauri\Cargo.toml', 'src-tauri\Cargo.lock')
    $rollbackBefore = @{}
    foreach ($relativePath in $rollbackFiles) {
        $rollbackBefore[$relativePath] = [System.IO.File]::ReadAllBytes([System.IO.Path]::Combine($rollbackFixture, $relativePath))
    }
    $lockedPath = [System.IO.Path]::Combine($rollbackFixture, 'src-tauri', 'tauri.conf.json')
    $lockStream = [System.IO.File]::Open($lockedPath, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::Read)
    try {
        Test-Throws 'A mid-transaction failure is reported after rollback' {
            & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $rollbackFixture -Confirm:$false
        } 'all modified files were restored'
    }
    finally {
        $lockStream.Dispose()
    }
    foreach ($relativePath in $rollbackFiles) {
        $afterBytes = [System.IO.File]::ReadAllBytes([System.IO.Path]::Combine($rollbackFixture, $relativePath))
        Test-Equal "Rollback restores $relativePath byte-for-byte" ([Convert]::ToBase64String($rollbackBefore[$relativePath])) ([Convert]::ToBase64String($afterBytes))
    }
    $leftovers = @(Get-ChildItem -LiteralPath $rollbackFixture -Recurse -File | Where-Object { $_.Name -match '\.version-sync\..+\.(tmp|bak)$' })
    Test-Equal 'Rollback leaves no transaction files' 0 $leftovers.Count

    $rollbackFailureFixture = New-VersionFixture -Parent $temporaryRoot
    $rollbackFailureOriginal = [System.IO.File]::ReadAllBytes([System.IO.Path]::Combine($rollbackFailureFixture, 'package.json'))
    $rollbackFailureLockedPath = [System.IO.Path]::Combine($rollbackFailureFixture, 'src-tauri', 'tauri.conf.json')
    $rollbackFailureStream = [System.IO.File]::Open($rollbackFailureLockedPath, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::Read)
    $rollbackCopyAction = {
        param([string]$BackupPath, [string]$DestinationPath)
        if ([System.IO.Path]::GetFileName($DestinationPath) -eq 'package.json') {
            throw 'synthetic rollback copy failure'
        }
        [System.IO.File]::Copy($BackupPath, $DestinationPath, $true)
    }
    $previousTestMode = $env:DESK_PET_VERSION_TEST_MODE
    $rollbackFailureMessage = $null
    try {
        $env:DESK_PET_VERSION_TEST_MODE = '1'
        try {
            & $versionScript -Version '0.2.0-beta.1' -RepositoryRoot $rollbackFailureFixture `
                -TestRollbackCopyAction $rollbackCopyAction -Confirm:$false | Out-Null
        }
        catch {
            $rollbackFailureMessage = $_.Exception.Message
        }
    }
    finally {
        $rollbackFailureStream.Dispose()
        $env:DESK_PET_VERSION_TEST_MODE = $previousTestMode
    }
    Test-True 'A rollback-copy failure is reported' ([bool]($rollbackFailureMessage -match 'rollback failed for: package.json')) $rollbackFailureMessage
    Test-Equal 'Rollback failure error does not reveal the fixture absolute path' $false ([bool]$rollbackFailureMessage.Contains($rollbackFailureFixture))
    $preservedBackups = @(Get-ChildItem -LiteralPath $rollbackFailureFixture -Recurse -File | Where-Object { $_.Name -match '\.version-sync\..+\.bak$' })
    Test-Equal 'Failed rollback preserves exactly one recovery backup' 1 $preservedBackups.Count
    if ($preservedBackups.Count -eq 1) {
        Test-Equal 'Preserved recovery backup contains the original package.json bytes' `
            ([Convert]::ToBase64String($rollbackFailureOriginal)) `
            ([Convert]::ToBase64String([System.IO.File]::ReadAllBytes($preservedBackups[0].FullName)))
    }
    $versionScriptText = Get-Content -LiteralPath $versionScript -Raw -Encoding UTF8
    Test-True 'Version tool uses PowerShell 7 AsHashtable for empty package-lock keys' ([bool]($versionScriptText -match 'PSVersionTable\.PSVersion\.Major\s*-ge\s*6[\s\S]+ConvertFrom-Json\s+-AsHashtable')) 'PowerShell 7 path'
    Test-True 'Version tool retains the Windows PowerShell 5.1 JSON fallback' ([bool]($versionScriptText -match 'System\.Web\.Extensions')) 'Windows PowerShell 5.1 path'
}
finally {
    if ([System.IO.Directory]::Exists($temporaryRoot)) {
        Remove-VersionFixtureTree -LiteralPath $temporaryRoot
    }
}

$results | Format-Table -AutoSize
$hostIsPowerShell51 = $PSVersionTable.PSVersion.Major -eq 5 -and $PSVersionTable.PSVersion.Minor -eq 1
[pscustomobject]@{ Name = 'Windows PowerShell 5.1 host'; Passed = $hostIsPowerShell51; Details = $PSVersionTable.PSVersion.ToString() } | Format-Table -AutoSize
if (@($results | Where-Object { -not $_.Passed }).Count -or -not $hostIsPowerShell51) {
    exit 1
}
